### ISSUE TITLE
Precise Details Needed

### ISSUE THREAD

**Issue by balajpri2021** [lathangi/Web-Docs-Assignments#1]
Dear Clients
I request that you provide the **Font-Family** to be used for the Website (e.g., Times New Roman, Helvetica, sans-serif, monospace, etc.) if you are confused kindly check the attached link for reference **[https://fonts.google.com/](url)** as well as provide the exact **Font-Sizes** for the headings and content. Also, if I'm not mistaken, is the color scheme for the web pages are **Light Brown** and **White** theme? Another clarification is that you have provided us with two variations of logo kindly let us  know which one to use. Please update us with precise information.

Thank you.

**Comment by lathangi** [comment]
Dear Ms Balaji,
Please use the font-family Monospace for the headings and content and Handwriting for any special descriptions of the headings(like the history of the company) that would create an aesthetic look to the webpage. 
The headings can be of size 40px and 24px for the content. The descriptions also is to be of size 24px.
Please use the image- https://github.com/lathangi/Web-Docs-Assignments/blob/main/assignment-2a/website-content/icon_2.svg as the logo.
You are right about the colors that need to be used.You can also use shades of pink where necessary.
We are sorry about the incomplete information.

**Comment by balajpri2021** [comment]
Thank you for the

**Comment by balajpri2021** [comment]
Dear Clients,
Concerning the font-family Monospace. 
As your website is about cakes and bread kind of bakery type, I recommend using **Times New Roman, serif** as the font-family for headings and content, which provides your website a pleasant and elegant appearance.  This will make your customers have a feel GOOD view when they visit your website. This is only a developer's recommendation. It is up to you to make the final decision. Please update on this regard.

Thank you.

**Comment by Philippaul** [comment]
Dear Developers,
Thank you for your recommendation. After going through our lecture pages remarkably from [https://www.b-tu.de/elearning/btu/pluginfile.php/437678/mod_resource/content/14/IntroCSS_LMS.html](url) , I think you can use sans-serif font family since those are ideal for screens. I personally like Verdana from sans-serif font family. I would also like your opinion about this. Please tell us about the virtual picture you have overall. Thank you!

**Comment by balajpri2021** [comment]
Thanks for letting us know I can provide you with a short screen-shot on how the font looks on using Verdana as well as Times New Roman so that you can have a better understanding and you can make your own decisions and finalize please take a look at the below images

**On using Verdana** 

![image](https://user-images.githubusercontent.com/93986263/148409716-d37d5d08-d768-4e82-9cef-e025bc13dea8.png)

**On using Times New Roman**

![image](https://user-images.githubusercontent.com/93986263/148409625-f3804ab2-e2a0-47d6-ab71-59dea5eec85d.png)


Please compare both the picture fonts and let us know which one you prefer. Also I personally recommend Times New Roman, serif as it fits well for your website which gives a classic look.

**Comment by balajpri2021** [comment]
Additionally  I request to confirm whether the color combination used is satisfied for you. If not kindly send the exact color code you wish to use I can recommend you to have a look at the website below:

[https://www.w3schools.com/colors/colors_palettes.asp](https://www.w3schools.com/colors/colors_palettes.asp  )

**Comment by Philippaul** [comment]
Dear developers,
   Thanks for your recommendations. While comparing the both fonts, Times New Roman looks good. So proceed in applying it to the site.
