### ISSUE TITLE
Clarification on video placement

### ISSUE THREAD

**Issue by balajpri2021** [lathangi/Web-Docs-Assignments#2]
Dear clients,
Please let us know if you require video placement on each and every page. Also, please review the provided video, as embedding and typing the direct link both play a different video. 

Also, please take a look at the previous issue as well and respond as soon as possible.

Thank you.

**Comment by lathangi** [comment]
Dear Ms Balaji,
We don't need the video to be displayed in every page. The video needs to be autoplayed as soon as the home page is loaded.
Please use the video I have attached here(https://www.youtube.com/watch?v=zhKifOulpb0).
