### ISSUE TITLE
Logo Placement

### ISSUE THREAD

**Issue by balajpri2021** [lathangi/Web-Docs-Assignments#3]
Dear Clients,
Please let me know where your logo will go. The positioning of the logo is unknown in the website-appearance-sample diagram. It is **recommended** that the logo should be placed in the **upper left corner for an effective brand recognition**. This issue is raised because  website-appearance-sample diagram has a **shopping icon** in the **place of logo**.  Please provide an update on this matter.

Thank you

**Comment by Philippaul** [comment]
![logoooooooo](https://user-images.githubusercontent.com/56349095/148529107-74e646de-323a-4d46-97f9-d63285106162.png)
Hello developers,
  please have the logo in the upper left corner of the site. You can refer the above image for clarification, but its a very raw picture so forgive us.
