### ISSUE TITLE
Request for Confirmation

### ISSUE THREAD

**Issue by balajpri2021** [lathangi/Web-Docs-Assignments#4]
Dear Clients, 
Please ensure that the visual design of the [Home Page](http://localhost:63342/assignment-2b/assignment-2b/Home.xhtml?_ijt=rau5nvdad1korpvaui13i4u5gm) is accessible please view only the home page as other pages are in process.

Designed according to the specified web-appearance-sample diagram provided with some alteration that may look good. It isn't the ultimate outcome. However, I'd appreciate your approval on the color and fonts chosen (need confirmation on   both #1), as well as the arrangement of the image, video and logo( #3 ). Please update with the necessary information as soon as possible.

Thank you.

**Comment by Philippaul** [comment]
Dear Developers,
    The link to the home-page is still local, so it cannot be accessed by us. So kindly make it online and tell us about it.
Thank You

**Comment by balajpri2021** [comment]
Dear @Philippaul ,
Please [Click On This link](https://htmlpreview.github.io/?https://github.com/lathangi/Web-Docs-Assignments/blob/main/assignment-2b/Home.xhtml) for the Home Page and update.

Thank you.

**Comment by balajpri2021** [comment]
Please also take a look at this [site](https://htmlpreview.github.io/?https://github.com/lathangi/Web-Docs-Assignments/blob/main/assignment-2b/CakesnPastries.xhtml)

**Comment by lathangi** [comment]
> 

The home page looks very monotonous, it would be great if you can include more colours.
The rest of the pages can be of the same colour.

**Comment by balajpri2021** [comment]
Dear Ms. Lathangi,
Please supply the precise color code for what you want. I have stated earlier in #1 but haven't got any response from your side. Also, you indicated that you require (light brown and pink). There are many shades of light brown and pink, so please go to [Color Picker](https://www.w3schools.com/colors/colors_picker.asp) and [Color Palettes](https://www.w3schools.com/colors/colors_palettes.asp) and tell us which one you like for text and which one you prefer for the background. Please respond as soon as possible so that we can deliver the result on schedule..

Thank you

**Comment by lathangi** [comment]
Dear Ms.Priyanka,
You can use the folowing colours as per your discretion to make the page look aesthetic and colourful. We do not have any specifications as per using a particular color for particular parts of the pages.
#d6cbd3
#eca1a6
#bdcebe
#ada397  (The above colors belong to the 2017 Palette).
For the shades of brown, you can use the elow colors:
#563f46
#4f3222
#625750

**Comment by balajpri2021** [comment]
> Dear @Philippaul , Please [Click On This link](https://htmlpreview.github.io/?https://github.com/lathangi/Web-Docs-Assignments/blob/main/assignment-2b/Home.xhtml) for the Home Page and update.
> 
> Thank you.

Dear Clients,
Request For Confirmation .

The  stated colors used are: 
For Text:
#eca1a6 

For Background : 
#563f46
#4f3222
#625750

Note that some colors did not blend/match hence they are omitted. Request for approval. (delayed response may affect the final result)

Thank you.

**Comment by lathangi** [comment]
Yes, we confirm.
