### ISSUE TITLE
Same Text caption for different images

### ISSUE THREAD

**Issue by balajpri2021** [lathangi/Web-Docs-Assignments#5]
Dear Clients,

Chocolate.txt and Vegan.txt appear to be the same text. It becomes a stumbling block while producing an **alternate text** for the image. This **alternate text** has been included so that people with disabilities may utilize it. This conforms with the Web Content Accessibility Guidelines (WCAG). Please provide Vegan.txt  with the **right alternate text** and update us as soon as possible.

Thank you.

**Comment by Philippaul** [comment]
Dear Developers,
      Thanks for bringing the issue. We will shortly update it in this issue.

**Comment by Philippaul** [comment]
[Vegan.txt](https://github.com/lathangi/Web-Docs-Assignments/files/7831579/Vegan.txt)
Dear Developers,
    Kindly make use of this for the vegan text. Please download the file.

**Comment by balajpri2021** [comment]
Dear @Philippaul,
I have asked you for the "alternative text" for image that you've provided, which is similar to a caption but not exactly a caption, this **alternative text** is used when the image can't be used for some reason. 

### Reasons:

1. It is used by screen readers which helps blind or visually challenged people to access it and know what the picture exactly is.  
2. It is displayed in place of the image in browsers if the image file hasn't loaded. 

### Note:
You've updated us with the making text which we already have. 

Please ask if you are unclear. Kindly update on this.

Thank you.

**Comment by lathangi** [comment]
Please use this alternative text: A vegan salad
