### ISSUE TITLE
Services Web Page

### ISSUE THREAD

**Issue by balajpri2021** [lathangi/Web-Docs-Assignments#6]
Dear Clients,
According to the [Web-design Diagram,](Web-Docs-Assignments/assignment-2a/website-content/website-design-diagram.pdf) you appear to have two sub-pages under the Services Web-page, but there are **no pictures** (as required by the [Web-sample appearance](Web-Docs-Assignments/assignment-2a/website-content/website-appearance-sample.pdf)) and the content is **insufficient** to make it a separate web-page. I'm curious to know if you'd like to combine two sub-pages into a single web page. i.e., instead of having a separate **Catering** and **Home Delivery** webpage, the Catering and Home Delivery content will be **incorporated** into the **Services Webpage**. Please respond as soon as possible.

Thank you.

**Comment by Philippaul** [comment]
Dear Developers,
      Yes you please combine catering and home delivery in a single page of services. We confirm this.
Thank You

**Comment by balajpri2021** [comment]
Dear Clients,
As there is very much less content and no images present to these sections. Kindly update us with images. 

Thank you.

**Comment by lathangi** [comment]
Please proceed with the content given.
