### ISSUE TITLE
Query regarding Social Media platforms 

### ISSUE THREAD

**Issue by balajpri2021** [lathangi/Web-Docs-Assignments#7]
Dear clients,
I'd want to know if you have any social media sites that we might include in the bottom. This might assist your consumers get one step closer to you.

Thank you.

**Comment by Philippaul** [comment]
Dear Developers,
  Yes please add a facebook to our site. We will shortly update the link to it.

**Comment by Philippaul** [comment]
Dear developers,
      Our facebook page is [https://www.facebook.com/Bread-and-ButterCo-Est1978-105310622049377/](url) . Kindly update it.
Thank you
