### ISSUE TITLE
Branches 

### ISSUE THREAD

**Issue by albenahm** [lathangi/Web-Docs-Assignments#8]
Hi, 

can you please provide more info and images for Branches. I need this info to make store with branches info. 

thanks in advance

**Comment by lathangi** [comment]
Can you please make your requirement more clear.

**Comment by albenahm** [comment]
I create the pages for the Store and branches.
I have only info about the name of branches and the Addresses with numbers. 
in pages  Hyderabad, Chennai and Bangalore what i have to present?

**Comment by lathangi** [comment]
Dear Mr.Ahmed,
You can list the branches with their respective details in the Store page.

**Comment by lathangi** [comment]
If your query is answered please close the issue.
