### ISSUE TITLE
Opening of GitHub Page

### ISSUE THREAD

**Issue by balajpri2021** [lathangi/Web-Docs-Assignments#9]
Dear Clients, 
It would be nice if you open either the[ GitHub Pages ](https://docs.github.com/en/pages) or[ Cloudflare Pages](https://pages.cloudflare.com/). Please update as soon as possible.

Thank you.

**Comment by Philippaul** [comment]
Dear developers,
   We would like to host the site on github pages and will update very soon

**Comment by lathangi** [comment]
Please find this link for the github pages-
https://lathangi.github.io/Web-Docs-Assignments/
